PythonCodeTask/PythonCodeTask/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^', include('User.urls', namespace='User')),
]

PythonCodeTask/User/urls.py
from django.conf.urls import url

from .views import (
    UserList,
    UserDetail,
    UserCreation,
    UserUpdate,
    UserDelete
)
import views

urlpatterns = [

    url(r'^$', UserList.as_view(), name='list'),
    url(r'^(?P<pk>\d+)$', UserDetail.as_view(), name='detail'),
    url(r'^new$', UserCreation.as_view(), name='new'),
    url(r'^edit/(?P<pk>\d+)$', UserUpdate.as_view(), name='edit'),
    url(r'^delete/(?P<pk>\d+)$', UserDelete.as_view(), name='delete'),
    url(r'^export/csv/$', views.export_users_csv, name='export_users_csv'),

]

PythonCodeTask/User/models.py
from __future__ import unicode_literals

from django.db import models
from datetime import date
import random

def random_string():
    return str(random.randint(1, 100))

class User(models.Model):
    Username = models.CharField(max_length=100)
    Birthday = models.DateField("Date", default=date.today) #Default Data Today
    Random = models.IntegerField(default = random_string)

PythonCodeTask/User/views.py
from django.core.urlresolvers import reverse_lazy

from django.views.generic import ListView
from django.views.generic.detail import DetailView
from django.views.generic.edit import (
    CreateView,
    UpdateView,
    DeleteView
)
import csv

from django.http import HttpResponse
from .models import User

class UserDelete(DeleteView):
    model = User
    success_url = reverse_lazy('User:list')

class UserList(ListView):
    model = User

class UserDetail(DetailView):
    model = User

class UserUpdate(UpdateView):
    model = User
    success_url = reverse_lazy('User:list')
    fields = ['Username', 'Birthday', 'Random']

class UserCreation(CreateView):
    model = User
    success_url = reverse_lazy('User:list')
    fields = ['Username', 'Birthday']

def export_users_csv(request):
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = 'attachment; filename="users.csv"'

    writer = csv.writer(response)
    writer.writerow(['Username', 'Birthday', 'Random'])

    users = User.objects.all().values_list('Username', 'Birthday', 'Random')
    for user in users:
        writer.writerow(user)

    return response

PythonCodeTask/User/templates/User/user_confirm_delete.html
{% extends "base.html" %}


{% block content %}
    <form method="post">{% csrf_token %}
        <h4>Are you sure you want to delete "{{ user.Username }}"?</h4>
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
    <hr />
    <p>
    	<a class="btn btn-primary" href="{% url "User:list" %}">Back</a>
    </p>
{% endblock content %}

PythonCodeTask/User/templates/User/user_detail.html
{% extends "base.html" %}
{% load customtags %}

{% block content %}
    <h2>Details for {{ user.Username }}</h2>
    <table class="table table-bordered table-stripped table-hover">
        <thead>
          <tr>
                <th>Username</th>
                <th>Birthday</th>
                <th>Eligible</th>
                <th>Random Number</th>
                <th>BizzFuzz</th>
                <th></th>
          </tr>
        </thead>
        <tbody>
            <tr>
                <td>{{ user.Username }}</td>
                <td>{{ user.Birthday }}</td>
                <td>{% check_eligible user.Birthday %}</td>
                <td>{{ user.Random }}</td>
                <td>{% bizzfuzz user.Random %}</td>
                <td>
                    <a href="{% url "User:edit" user.id %}">Edit</a> |
                    <a href="{% url "User:delete" user.id %}">Delete</a>
                </td>
            </tr>
        </tbody>
    </table>
    <p>
        <a class="btn btn-primary" href="{% url "User:list" %}">Back</a>
    </p>
{% endblock content %}

PythonCodeTask/User/templates/User/user_form.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
    <form method="post">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input class="btn btn-primary" type="submit" value="Submit" />
    </form>
    <br />
    <p>
        <a class="btn btn-primary" href="{% url "User:list" %}">Back</a>
    </p>
{% endblock content %}

PythonCodeTask/User/templates/User/user_list.html
{% extends "base.html" %}
{% load customtags %}
{% block content %}
    <h2>User Management</h2>

    <div class="btn-group">
        <a class="btn btn-primary" href="{% url "User:new" %}">Add a User</a>
        <a class="btn btn-primary" href="{% url "User:export_users_csv" %}">Export all users</a>
    </div>
    <table class="table table-bordered table-stripped table-hover">
        <thead>
          <tr>
                <th>Username</th>
                <th>Birthday</th>
                <th>Eligible</th>
                <th>Random Number</th>
                <th>BizzFuzz</th>
                <th></th>
          </tr>
        </thead>
        <tbody>
            {% for user in object_list %}
                <tr>
                    <td>{{ user.Username }}</td>
                    <td>{{ user.Birthday }}</td>
                    <td>{% check_eligible user.Birthday %}</td>
                    <td>{{ user.Random }}</td>
                    <td>{% bizzfuzz user.Random %}</td>
                    <td>
                        <a href="{% url "User:detail" user.id %}">Show</a> |
                        <a href="{% url "User:edit" user.id %}">Edit</a> |
                        <a href="{% url "User:delete" user.id %}">Delete</a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
{% endblock content %}

PythonCodeTask/templates/base.html
{% load staticfiles %}{% spaceless %}
{% load bootstrap3 %}
<!doctype html>
    <html class="no-js" lang="">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
        <title>{% block title %}{% endblock %} :: Python Test Project</title>
        <meta name="description" content="{% block description %}{% endblock %}">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        {% bootstrap_css %}
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        {% bootstrap_javascript %}
        <!--[if lt IE 9]>
            <script src="//html5shiv.googlecode.com/svn/trunk/html5.js"></script>
            <script>window.html5 || document.write('<script src="{{ STATIC_URL }}libs/html5shiv.js"><\/script>')</script>
        <![endif]-->
    </head>
    <body>
        <!--[if lt IE 8]>
        <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->
        <div class="container-fluid">
            <div class="row">
                <div class="col-xs-12">
                    <h1>Python Test Project</h1>
                    <hr>
                    {% block content %}{% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>
{% endspaceless %}